#!/usr/bin/env bash
# Inject backend URL into frontend/src/config.js from azd env values.
# Run AFTER `azd provision` (or `azd up`), BEFORE `azd deploy` for the frontend service.
set -euo pipefail

cd "$(dirname "$0")/.."

BACKEND_URL="${BACKEND_URL:-$(azd env get-value BACKEND_URL 2>/dev/null || true)}"

if [[ -z "$BACKEND_URL" ]]; then
  echo "⚠️  BACKEND_URL not found in azd env. Run 'azd provision' first." >&2
  exit 1
fi

cat > frontend/src/config.js <<EOF
// Auto-generated by scripts/inject-config.sh on $(date -u +%FT%TZ)
window.__BACKEND__ = "${BACKEND_URL}";
EOF

echo "✅ Injected BACKEND_URL=${BACKEND_URL} into frontend/src/config.js"
